//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BNB.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BNB.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About author.
        /// </summary>
        public static string AboutAuthor {
            get {
                return ResourceManager.GetString("AboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About university.
        /// </summary>
        public static string AboutUniversity {
            get {
                return ResourceManager.GetString("AboutUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new sensor info.
        /// </summary>
        public static string AddingNewSensorInfo {
            get {
                return ResourceManager.GetString("AddingNewSensorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new sensor.
        /// </summary>
        public static string AddSensorError {
            get {
                return ResourceManager.GetString("AddSensorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill all required (*) fileds.
        /// </summary>
        public static string AllFieldsRequired {
            get {
                return ResourceManager.GetString("AllFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our API for your projects..
        /// </summary>
        public static string ApiMsg {
            get {
                return ResourceManager.GetString("ApiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 82100, Drohobych.
        /// </summary>
        public static string AuthorAddress {
            get {
                return ResourceManager.GetString("AuthorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author information.
        /// </summary>
        public static string AuthorInformation {
            get {
                return ResourceManager.GetString("AuthorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dmytro Novak.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building name.
        /// </summary>
        public static string BuildingName {
            get {
                return ResourceManager.GetString("BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for other users.
        /// </summary>
        public static string BuildingNameTooltip {
            get {
                return ResourceManager.GetString("BuildingNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its required fore future filtering information.
        /// </summary>
        public static string CityTooltip {
            get {
                return ResourceManager.GetString("CityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The blind are not blind.
        /// </summary>
        public static string Company_description {
            get {
                return ResourceManager.GetString("Company_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates from map.
        /// </summary>
        public static string CoordinatesFromMap {
            get {
                return ResourceManager.GetString("CoordinatesFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom map to preffered location and add marker. Its required to show to users existing markers.
        /// </summary>
        public static string CoordinatesFromMapTooltip {
            get {
                return ResourceManager.GetString("CoordinatesFromMapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its required for future filtering information.
        /// </summary>
        public static string CountryTooltip {
            get {
                return ResourceManager.GetString("CountryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string CreateSensorDateText {
            get {
                return ResourceManager.GetString("CreateSensorDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;January&quot;, &quot;February&quot;, &quot;March&quot;,
        ///            &quot;April&quot;, &quot;May&quot;, &quot;June&quot;, &quot;July&quot;,
        ///            &quot;August&quot;, &quot;September&quot;, &quot;October&quot;,
        ///            &quot;November&quot;, &quot;December&quot;.
        /// </summary>
        public static string DateTimeMonthArray {
            get {
                return ResourceManager.GetString("DateTimeMonthArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for more info about sensor location or additional info.
        /// </summary>
        public static string DetailsTooltip {
            get {
                return ResourceManager.GetString("DetailsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We send you copy of form for sensor with with key and instructions.
        /// </summary>
        public static string EmailTooltip {
            get {
                return ResourceManager.GetString("EmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Loading map.
        /// </summary>
        public static string ErrorWhileLoadingMap {
            get {
                return ResourceManager.GetString("ErrorWhileLoadingMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending error.
        /// </summary>
        public static string FeedbackAddFail {
            get {
                return ResourceManager.GetString("FeedbackAddFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback was successfuly received.
        /// </summary>
        public static string FeedbackAddSuccess {
            get {
                return ResourceManager.GetString("FeedbackAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your idea/proposition etc...
        /// </summary>
        public static string FeedbackDetailsName {
            get {
                return ResourceManager.GetString("FeedbackDetailsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details for more info about sensor location or additional info.
        /// </summary>
        public static string FeedbackDetailsTooltip {
            get {
                return ResourceManager.GetString("FeedbackDetailsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want, we send request status on this email.
        /// </summary>
        public static string FeedbackEmailTooltip {
            get {
                return ResourceManager.GetString("FeedbackEmailTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback form.
        /// </summary>
        public static string FeedbackForm {
            get {
                return ResourceManager.GetString("FeedbackForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can leave recomendations, ask a question or just say &quot;thank you&quot;, or no:)..
        /// </summary>
        public static string FeedbackFormText {
            get {
                return ResourceManager.GetString("FeedbackFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback information.
        /// </summary>
        public static string FeedbackInformation {
            get {
                return ResourceManager.GetString("FeedbackInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi. I think....
        /// </summary>
        public static string FeedbackPlaceholder {
            get {
                return ResourceManager.GetString("FeedbackPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: The Geolocation service failed..
        /// </summary>
        public static string GeolocationError {
            get {
                return ResourceManager.GetString("GeolocationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Your browser doesn\&apos;t support geolocation..
        /// </summary>
        public static string GeolocationSuppportError {
            get {
                return ResourceManager.GetString("GeolocationSuppportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction.
        /// </summary>
        public static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download app.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location from map.
        /// </summary>
        public static string LocationFromMap {
            get {
                return ResourceManager.GetString("LocationFromMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom map to preffered location and add marker. Its required to show to users existing markers.
        /// </summary>
        public static string LocationFromMapTooltip {
            get {
                return ResourceManager.GetString("LocationFromMapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location information.
        /// </summary>
        public static string LocationInformation {
            get {
                return ResourceManager.GetString("LocationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blind people are not blind now. Now, there is a wonderful solution that will simplify the lives of blind people and help them get around in the premises.
        /// </summary>
        public static string MainPageMessage {
            get {
                return ResourceManager.GetString("MainPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource is under development, contains errors and no refined functionality..
        /// </summary>
        public static string MainWarning {
            get {
                return ResourceManager.GetString("MainWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string MarkerAddress {
            get {
                return ResourceManager.GetString("MarkerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string MarkerAuthor {
            get {
                return ResourceManager.GetString("MarkerAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string MarkerDetails {
            get {
                return ResourceManager.GetString("MarkerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building name.
        /// </summary>
        public static string MarkerLocation {
            get {
                return ResourceManager.GetString("MarkerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full marker address.
        /// </summary>
        public static string MarkerTapAddress {
            get {
                return ResourceManager.GetString("MarkerTapAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates.
        /// </summary>
        public static string MarkerTapCoordinates {
            get {
                return ResourceManager.GetString("MarkerTapCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker details for new sensor.
        /// </summary>
        public static string MarkerTapMsg {
            get {
                return ResourceManager.GetString("MarkerTapMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to coordinates and full address will be dublicated to \&apos;add sensor\&apos; form below.
        /// </summary>
        public static string MarkerTapTooltip {
            get {
                return ResourceManager.GetString("MarkerTapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor text.
        /// </summary>
        public static string MarkerText {
            get {
                return ResourceManager.GetString("MarkerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last changes.
        /// </summary>
        public static string ModifiedSensorDateText {
            get {
                return ResourceManager.GetString("ModifiedSensorDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To know who add sensor.
        /// </summary>
        public static string NameTooltip {
            get {
                return ResourceManager.GetString("NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click on icons for tooltip.
        /// </summary>
        public static string NoteText {
            get {
                return ResourceManager.GetString("NoteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave feedback.
        /// </summary>
        public static string PageNotFoundLeaveFeedback {
            get {
                return ResourceManager.GetString("PageNotFoundLeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, somehow, it seems the page you are trying to open is no longer available or moved to a new address..
        /// </summary>
        public static string PageNotFoundMsg {
            get {
                return ResourceManager.GetString("PageNotFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are certain that something went wrong and the page should be displayed on request, leave us feedback with details of your actions. We will try to fix the problem..
        /// </summary>
        public static string PageNotFoundPropositions {
            get {
                return ResourceManager.GetString("PageNotFoundPropositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want a feedback from you about my request status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required fields.
        /// </summary>
        public static string RequiredFields {
            get {
                return ResourceManager.GetString("RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to return on the top page.
        /// </summary>
        public static string ReturnUp {
            get {
                return ResourceManager.GetString("ReturnUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor were added successfuly..
        /// </summary>
        public static string SensorAdded {
            get {
                return ResourceManager.GetString("SensorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor information.
        /// </summary>
        public static string SensorInformation {
            get {
                return ResourceManager.GetString("SensorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor MAC.
        /// </summary>
        public static string SensorMAC {
            get {
                return ResourceManager.GetString("SensorMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC address is required for binding your data to your sensor, information about device MAC address you can find  on instruction page.
        /// </summary>
        public static string SensorMACTooltip {
            get {
                return ResourceManager.GetString("SensorMACTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor text.
        /// </summary>
        public static string SensorText {
            get {
                return ResourceManager.GetString("SensorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for playing this text to blid peoples.
        /// </summary>
        public static string SensorTextTooltip {
            get {
                return ResourceManager.GetString("SensorTextTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave feedback.
        /// </summary>
        public static string ServerErrorLeaveFeedback {
            get {
                return ResourceManager.GetString("ServerErrorLeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh, somehow, it seems we had a problem with the server while processing our request..
        /// </summary>
        public static string ServerErrorMsg {
            get {
                return ResourceManager.GetString("ServerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be nice and easier for us to fix the error if you leave a feedback with details about how you encountered an error..
        /// </summary>
        public static string ServerErrorPropositions {
            get {
                return ResourceManager.GetString("ServerErrorPropositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit sensor info.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click on icons for tooltip.
        /// </summary>
        public static string TooltipMsg {
            get {
                return ResourceManager.GetString("TooltipMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 79013, Lviv, Stepana Bandery St, 12.
        /// </summary>
        public static string UniversityAddress {
            get {
                return ResourceManager.GetString("UniversityAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lviv Polytechnic National University.
        /// </summary>
        public static string UniversityName {
            get {
                return ResourceManager.GetString("UniversityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave feedback.
        /// </summary>
        public static string UnknownErrorLeaveFeedback {
            get {
                return ResourceManager.GetString("UnknownErrorLeaveFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, there was an unknown error..
        /// </summary>
        public static string UnknownErrorMsg {
            get {
                return ResourceManager.GetString("UnknownErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be nice and easier for us to fix the error if you leave a feedback with details about how you encountered an error..
        /// </summary>
        public static string UnknownErrorPropositions {
            get {
                return ResourceManager.GetString("UnknownErrorPropositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
